### ISSUE TITLE
Allow [some] backport PRs to be automatically merged

### ISSUE THREAD

**Issue by codebytere** [electron/trop#118]
Most backport PRs benefit from the human approval required to merge them into release line branches, but given a few conditions I think it would be a positive to at least _enable_ trop to merge its own backports.

Conditions for approval:
1. All Checks are passing or neutral
2. Semantic PR type falls in a certain category (not a `fix`, perhaps?)
3. A mysterious third condition (a label? some other indicator?)

cc @MarshallOfSound what are your thoughts here? My only hard opinion so far is on `1` in that i don't think we should ever consider automerge for non-green PRs even if they're flaking.

**Comment by MarshallOfSound** [comment]
Proposed conditions:

1. Trop raised the pull request
1. There are no additional commits made by a non-trop user (this will be hard to verify until Trop pushes signed commits)
1. All Checks are passing or neutral
1. A user in the `@mergers` group has approved the backport

Still not 100% on these, probs need to think through the implications a bit

**Comment by codebytere** [comment]
Closing as i think the current system is generally a better one and this will introduce too many edge cases.
