### ISSUE TITLE
error: Failed to merge in the changes

### ISSUE THREAD

**Issue by mehdi-vaadin** [electron/trop#144]
I started `trop` locally based on local-setup guide and I'm trying to use it on one of my repositories. I create a pull request with another user and label it `target/old`. After I merge the PR, I get this error:
```
error: Failed to merge in the changes.
```
Here is the full log [trop.log](https://github.com/electron/trop/files/4170995/trop.log).

My Node version is `12.14.01 and npm version is `6.1.3.4`.

**Comment by codebytere** [comment]
This is a git issue, not a trop issue.
