### ISSUE TITLE
Cherry pick squash commit instead of each individual commit

### ISSUE THREAD

**Issue by codebytere** [electron/trop#185]
As in title. Cherry picking each commit can lead to failures on backports, as seen in https://github.com/electron/electron/pull/25198

**Comment by MarshallOfSound** [comment]
This should be "in addition to".  It should be fallback / primary behavior where we try both strategies.  One might work in some cases and not the other 🤔

**Comment by codebytere** [comment]
@MarshallOfSound i thought about this and couldn't think of a scenario the squash cherry pick would fail and the individual picks would succeed - can you? I'm not against a fallback but if we can't think of an edge case for this i'd rather just do the squash pick always

**Comment by MarshallOfSound** [comment]
Certain things like renames then changes can be mis detected as a removal then an addition if the commits are squashed.  Having the full history is sometimes better
