### ISSUE TITLE
Issue while setting up trop in locals

### ISSUE THREAD

**Issue by Jassi10000** [electron/trop#222]
Am trying set up <code>trop</code> in my locals , but got struck at one point

On visiting this url , https://github.com/electron/trop/blob/master/docs/local-setup.md
I was following all the steps until I clicked the <code> Create Github App </code> after filling all the necessary credentials.
In the steps , there is no reference of what to put in  " Homepage URL of the App "

Can someone help me with this ?

**Comment by codebytere** [comment]
hey @Jassi10000 - trop is a Probot app, so you can find that info [here](https://probot.github.io/docs/development/#manually-configuring-a-github-app) and [here](https://probot.github.io/docs/deployment/#register-the-github-app). 

For that specific field, I would simply put the url to your fork.
