### ISSUE TITLE
Where did the name come from?

### ISSUE THREAD

**Issue by zeke** [electron/trop#23]
Going to wager a guess that's probably wrong: It's from the French "trop" meaning "too much", because it's too much work for humans to do this kind of work.

cc @codebytere @MarshallOfSound

**Comment by MarshallOfSound** [comment]
Heh, it's quite literally back "port" 😄

**Comment by ckerr** [comment]
As in, p-o-r-t t-r-o-p

**Comment by zeke** [comment]
🔁
