### ISSUE TITLE
Handle new release branches for existing PRs

### ISSUE THREAD

**Issue by erickzhao** [electron/trop#248]
As a maintainer, I want trop to be aware of new release branches for open PRs that already have target labels.

Take this scenario:
* I open a fix PR when Electron's latest release branch is `24-x-y` that targets Electron v24+.
* I add the `target/24-x-y` label via trop.
* Some time passes, and the `25-x-y` branch is cut.
* I get the PR merged and trop backports to the `24-x-y` branch.

In this case, `25-x-y` will be missing the commit. This kind of error happens somewhat often, in my experience. It would be nice if trop would automatically add the `target/25-x-y` label when that branch is cut. Alternatively, some kind of warning would be nice as well.

**Comment by dsanders11** [comment]
Closing this as it is now handled by automation on `e/e` (via https://github.com/electron/electron/pull/38181).
