### ISSUE TITLE
Consider adding support for deleted branches

### ISSUE THREAD

**Issue by ckerr** [electron/trop#27]
As per the discussion with @alexeykuzmin in the #trop Slack channel, and also prompted by my own user error twice in the last few days of adding a label _before_ restoring the branch :stuck_out_tongue: 

This isn't a blocker, but it is a wart and trop would be more useful if it didn't require the branch to be extant.

**Comment by jfirebaugh** [comment]
So is the note at the bottom of [usage.md](https://github.com/electron/trop/blob/master/docs/usage.md) no longer necessary?

> **Note**
> * If you delete a branch immediately after merging its associated pull request, trop will be unable to find it and the backports will fail
