### ISSUE TITLE
Support Heroku-24 Stack

### ISSUE THREAD

**Issue by dsanders11** [electron/trop#303]
[The Heroku-24 stack](https://devcenter.heroku.com/articles/heroku-24-stack) removes Git at runtime which is problematic since trop needs it. So we need to tweak our usage of Heroku here to ensure Git is present. In the meantime we're trying to stay pinned to the Heroku-22 stack.

We may also want to add a check for Git early on and fail more loudly if it's not found. Currently the failure mode is somewhat silent and just goes down the unable to automatically backport path.

**Comment by erickzhao** [comment]
I think the path forward according to [this Help Centre ticket](https://help.heroku.com/IYRYW6VB/how-do-i-install-additional-software-packages-that-my-application-requires) would be to use [heroku-buildpath-apt](https://github.com/heroku/heroku-buildpack-apt) in combination with a [multi-buildpack setup](https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app) to essentially `apt-get install git` in the Heroku image.
