### ISSUE TITLE
feat: add support for rolling libchromiumcontent submodule

### ISSUE THREAD

**Issue by ckerr** [electron/trop#37]
Two parts to this:

1. This is a small chore but one we do frequently, is easy to automate, and will be needed until the gyp-based releases are EOLed (sometime mid-2019?). So having a bot to do this would be handy.

2. I'm not sure if `trop` is the right place for it, since this is kind of domain-specific and trop is intended to be more generic. Is it in trop's mandate to do something like automated submodule bumps?

**Comment by alexeykuzmin** [comment]
Can we create a new bot for this task?

**Comment by MarshallOfSound** [comment]
IMO this should be a new bot :smile:
