### ISSUE TITLE
handle multiple branches in a single comment

### ISSUE THREAD

**Issue by ckerr** [electron/trop#38]
Use case is [this thread](https://github.com/electron/electron/pull/14030#issuecomment-412380196):

```text
/trop run backport-to 2-0-x
/trop run backport-to 3-0-x
```
```text￼
The backport process for this PR has been manually initiated, sending your 1's and 0's to "2-0-x" here we go! :D
```

Would be nice if we could specify multiple commands in the same comment.

Alternately, to specify more than one branch in the `backport-to` command, e.g.:
```text
/trop run backport-to 2-0-x, 3-0-x
```

**Comment by codebytere** [comment]
Enabled by https://github.com/electron/trop/pull/40 :)
