### ISSUE TITLE
Fall back to a three-way merge when patching

### ISSUE THREAD

**Issue by ckerr** [electron/trop#45]
Trop sometimes fails for reasons unknown.

Example:

https://github.com/electron/electron/pull/14297 [failed](https://github.com/electron/electron/pull/14297#issuecomment-416310703) going back to `#2-0-x`; however, when I ran it  manually a cherry-pick ran cleanly:

```sh
~/src/electron/electron/2-0-x   2-0-x ● $ git cherry-pick  a43a292
[2-0-x c334881b9] fix: dont parse arguments after a -- in the inspector (#14297)
 Author: Samuel Attard <samuel.r.attard@gmail.com>
 Date: Mon Aug 27 10:50:23 2018 -0700
 2 files changed, 10 insertions(+), 2 deletions(-)
```

**Comment by ckerr** [comment]
Discussion from @MarshallOfSound in `#bots`:

> @here clear to go again, although a suspiciously large number of trop failures occurred in a row, everything is working as intended.  In other news we should probably update trop to fall back to a 3 way merge when applying patches :slightly_smiling_face: all these failures would have been avoided then

**Comment by deepak1556** [comment]
Trop backport failed in a recent PR merge https://github.com/electron/electron/pull/14324 , but manual cherry pick ran cleanly.

```sh
$ git cherry-pick edd5c4b9bbac3e612627407c057ca25170b7cf9d
[backport-14324-3-x 16e2062ea] fix: use OS process handle to clear object registry (#14324)
 Author: Robo <hop2deep@gmail.com>
 Date: Wed Aug 29 00:02:46 2018 +0530
 4 files changed, 10 insertions(+), 7 deletions(-)
```

Not sure whats the issue, just wanted to report it as suggested by @ckerr

**Comment by MarshallOfSound** [comment]
The fix hasn't been deployed yet
