### ISSUE TITLE
Trop doesn't create branch/PR for failed backports

### ISSUE THREAD

**Issue by nitsakh** [electron/trop#67]
Currently trop doesn't create a PR for failed backports. It would be nice if it created the PR and probably mentioned the original dev to resolve the merge conflicts. The dev can then just update this trop created PR/branch.

**Comment by MarshallOfSound** [comment]
@nitsakh For safety reasons the trop PR is made from a fork of Electron which no one else has write access to.  This way we know that PRs from trops are truly backported and not human-created changes.  I feel if trop made a PR and then a human updated that PR it may misrepresent the changes to reviewers.

Also, we apply patches per-commit in the original PR so it's possible the conflict trop finds won't include all the changes in the original PR meaning the human would have to manually choose the remaining commits anyway.

We do however provide the failed patch application through the GitHub checks API so you can see what the conflict is.
